/**
 * service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExampleHat', 'model/ExampleSize', 'api/HaberdasherApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ExampleHat'), require('./model/ExampleSize'), require('./api/HaberdasherApi'));
  }
}(function(ApiClient, ExampleHat, ExampleSize, HaberdasherApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Serviceproto = require('index'); // See note below*.
   * var xxxSvc = new Serviceproto.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Serviceproto.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Serviceproto.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Serviceproto.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version version not set
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ExampleHat model constructor.
     * @property {module:model/ExampleHat}
     */
    ExampleHat: ExampleHat,
    /**
     * The ExampleSize model constructor.
     * @property {module:model/ExampleSize}
     */
    ExampleSize: ExampleSize,
    /**
     * The HaberdasherApi service constructor.
     * @property {module:api/HaberdasherApi}
     */
    HaberdasherApi: HaberdasherApi
  };

  return exports;
}));
