/**
 * service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Serviceproto) {
      root.Serviceproto = {};
    }
    root.Serviceproto.ExampleSize = factory(root.Serviceproto.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ExampleSize model module.
   * @module model/ExampleSize
   * @version version not set
   */

  /**
   * Constructs a new <code>ExampleSize</code>.
   * Size is passed when requesting a new hat to be made. It&#39;s always measured in inches.
   * @alias module:model/ExampleSize
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ExampleSize</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExampleSize} obj Optional instance to populate.
   * @return {module:model/ExampleSize} The populated <code>ExampleSize</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('inches')) {
        obj['inches'] = ApiClient.convertToType(data['inches'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} inches
   */
  exports.prototype['inches'] = undefined;



  return exports;
}));


