/*
 * service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Size is passed when requesting a new hat to be made. It&#39;s always measured in inches.
 */
@ApiModel(description = "Size is passed when requesting a new hat to be made. It's always measured in inches.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-26T23:54:16.913Z")
public class ExampleSize {
  @SerializedName("inches")
  private Integer inches = null;

  public ExampleSize inches(Integer inches) {
    this.inches = inches;
    return this;
  }

   /**
   * Get inches
   * @return inches
  **/
  @ApiModelProperty(value = "")
  public Integer getInches() {
    return inches;
  }

  public void setInches(Integer inches) {
    this.inches = inches;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExampleSize exampleSize = (ExampleSize) o;
    return Objects.equals(this.inches, exampleSize.inches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExampleSize {\n");
    
    sb.append("    inches: ").append(toIndentedString(inches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

