# coding: utf-8

"""
    service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.example_size import ExampleSize  # noqa: E501
from swagger_client.rest import ApiException


class TestExampleSize(unittest.TestCase):
    """ExampleSize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExampleSize(self):
        """Test ExampleSize"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.example_size.ExampleSize()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
