/* 
 * service.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Size is passed when requesting a new hat to be made. It&#39;s always measured in inches.
    /// </summary>
    [DataContract]
    public partial class ExampleSize :  IEquatable<ExampleSize>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExampleSize" /> class.
        /// </summary>
        /// <param name="Inches">Inches.</param>
        public ExampleSize(int? Inches = default(int?))
        {
            this.Inches = Inches;
        }
        
        /// <summary>
        /// Gets or Sets Inches
        /// </summary>
        [DataMember(Name="inches", EmitDefaultValue=false)]
        public int? Inches { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExampleSize {\n");
            sb.Append("  Inches: ").Append(Inches).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExampleSize);
        }

        /// <summary>
        /// Returns true if ExampleSize instances are equal
        /// </summary>
        /// <param name="input">Instance of ExampleSize to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExampleSize input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Inches == input.Inches ||
                    (this.Inches != null &&
                    this.Inches.Equals(input.Inches))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Inches != null)
                    hashCode = hashCode * 59 + this.Inches.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
