/* 
 * service.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExampleSize
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExampleSizeTests
    {
        // TODO uncomment below to declare an instance variable for ExampleSize
        //private ExampleSize instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExampleSize
            //instance = new ExampleSize();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExampleSize
        /// </summary>
        [Test]
        public void ExampleSizeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExampleSize
            //Assert.IsInstanceOfType<ExampleSize> (instance, "variable 'instance' is a ExampleSize");
        }


        /// <summary>
        /// Test the property 'Inches'
        /// </summary>
        [Test]
        public void InchesTest()
        {
            // TODO unit test for the property 'Inches'
        }

    }

}
