/**
 * service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExampleHat', 'model/ExampleSize'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ExampleHat'), require('../model/ExampleSize'));
  } else {
    // Browser globals (root is window)
    if (!root.Serviceproto) {
      root.Serviceproto = {};
    }
    root.Serviceproto.HaberdasherApi = factory(root.Serviceproto.ApiClient, root.Serviceproto.ExampleHat, root.Serviceproto.ExampleSize);
  }
}(this, function(ApiClient, ExampleHat, ExampleSize) {
  'use strict';

  /**
   * Haberdasher service.
   * @module api/HaberdasherApi
   * @version version not set
   */

  /**
   * Constructs a new HaberdasherApi. 
   * @alias module:api/HaberdasherApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the makeHat operation.
     * @callback module:api/HaberdasherApi~makeHatCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExampleHat} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * MakeHat produces a hat of mysterious, randomly-selected color!
     * @param {module:model/ExampleSize} body 
     * @param {module:api/HaberdasherApi~makeHatCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExampleHat}
     */
    this.makeHat = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling makeHat");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ExampleHat;

      return this.apiClient.callApi(
        '/twirp/twitch.twirp.example.Haberdasher/MakeHat', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
