# coding: utf-8

"""
    service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ExampleHat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'size': 'int',
        'color': 'str',
        'name': 'str'
    }

    attribute_map = {
        'size': 'size',
        'color': 'color',
        'name': 'name'
    }

    def __init__(self, size=None, color=None, name=None):  # noqa: E501
        """ExampleHat - a model defined in Swagger"""  # noqa: E501

        self._size = None
        self._color = None
        self._name = None
        self.discriminator = None

        if size is not None:
            self.size = size
        if color is not None:
            self.color = color
        if name is not None:
            self.name = name

    @property
    def size(self):
        """Gets the size of this ExampleHat.  # noqa: E501

        The size of a hat should always be in inches.  # noqa: E501

        :return: The size of this ExampleHat.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this ExampleHat.

        The size of a hat should always be in inches.  # noqa: E501

        :param size: The size of this ExampleHat.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def color(self):
        """Gets the color of this ExampleHat.  # noqa: E501

        The color of a hat will never be 'invisible', but other than that, anything is fair game.  # noqa: E501

        :return: The color of this ExampleHat.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this ExampleHat.

        The color of a hat will never be 'invisible', but other than that, anything is fair game.  # noqa: E501

        :param color: The color of this ExampleHat.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def name(self):
        """Gets the name of this ExampleHat.  # noqa: E501

        The name of a hat is it's type. Like, 'bowler', or something.  # noqa: E501

        :return: The name of this ExampleHat.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ExampleHat.

        The name of a hat is it's type. Like, 'bowler', or something.  # noqa: E501

        :param name: The name of this ExampleHat.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExampleHat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
