=begin
#service.proto

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ExampleSize
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExampleSize' do
  before do
    # run before each test
    @instance = SwaggerClient::ExampleSize.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExampleSize' do
    it 'should create an instance of ExampleSize' do
      expect(@instance).to be_instance_of(SwaggerClient::ExampleSize)
    end
  end
  describe 'test attribute "inches"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

