--[[ 
  service.proto
 
  No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 
  OpenAPI spec version: version not set
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- example_size class
local example_size = {}
local example_size_mt = {
	__name = "example_size";
	__index = example_size;
}

local function cast_example_size(t)
	return setmetatable(t, example_size_mt)
end

local function new_example_size(inches)
	return cast_example_size({
		["inches"] = inches;
	})
end

return {
	cast = cast_example_size;
	new = new_example_size;
}
