/*
 * service.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Size is passed when requesting a new hat to be made. It's always measured in inches.
type ExampleSize struct {

	Inches int32 `json:"inches,omitempty"`
}
