/*
 * service.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A Hat is a piece of headwear made by a Haberdasher.
type ExampleHat struct {

	// The size of a hat should always be in inches.
	Size int32 `json:"size,omitempty"`

	// The color of a hat will never be 'invisible', but other than that, anything is fair game.
	Color string `json:"color,omitempty"`

	// The name of a hat is it's type. Like, 'bowler', or something.
	Name string `json:"name,omitempty"`
}
